//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderSystem.WPF.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WpfOrderResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WpfOrderResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OrderSystem.WPF.Resources.WpfOrderResources", typeof(WpfOrderResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toevoegen.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bestelling toevoegen.
        /// </summary>
        public static string AddOrder {
            get {
                return ResourceManager.GetString("AddOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bestelregel toevoegen.
        /// </summary>
        public static string AddOrderLine {
            get {
                return ResourceManager.GetString("AddOrderLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product toevoegen.
        /// </summary>
        public static string AddProduct {
            get {
                return ResourceManager.GetString("AddProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Productgroep toevoegen.
        /// </summary>
        public static string AddProductGroup {
            get {
                return ResourceManager.GetString("AddProductGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annuleren.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weet u zeker dat u de wijzigingen wilt annuleren?.
        /// </summary>
        public static string CancelPendingChangesQuestion {
            get {
                return ResourceManager.GetString("CancelPendingChangesQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Kies een product --.
        /// </summary>
        public static string ChooseProduct {
            get {
                return ResourceManager.GetString("ChooseProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Kies een productgroep --.
        /// </summary>
        public static string ChooseProductgroup {
            get {
                return ResourceManager.GetString("ChooseProductgroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weet u zeker dat u de bestelling d.d. {0} wilt verwijderen?.
        /// </summary>
        public static string ConfirmDeleteOrder {
            get {
                return ResourceManager.GetString("ConfirmDeleteOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weet u zeker dat u de bestelregel voor &quot;{0}&quot; wilt verwijderen?.
        /// </summary>
        public static string ConfirmDeleteOrderLine {
            get {
                return ResourceManager.GetString("ConfirmDeleteOrderLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weet u zeker dat u product &quot;{0}&quot; wilt laten vervallen? Dit proces is onomkeerbaar!.
        /// </summary>
        public static string ConfirmDeleteProduct {
            get {
                return ResourceManager.GetString("ConfirmDeleteProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weet u zeker dat u product &quot;{0}&quot; wilt laten vervallen? Dit is niet terug te draaien!.
        /// </summary>
        public static string ConfirmDeleteProductGroup {
            get {
                return ResourceManager.GetString("ConfirmDeleteProductGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verwijderen.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bestelling verwijderen.
        /// </summary>
        public static string DeleteOrder {
            get {
                return ResourceManager.GetString("DeleteOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bestelregel verwijderen.
        /// </summary>
        public static string DeleteOrderLine {
            get {
                return ResourceManager.GetString("DeleteOrderLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product verwijderen.
        /// </summary>
        public static string DeleteProduct {
            get {
                return ResourceManager.GetString("DeleteProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Productgroep laten vervallen.
        /// </summary>
        public static string DeleteProductGroup {
            get {
                return ResourceManager.GetString("DeleteProductGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wijzigen.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bestelling wijzigen.
        /// </summary>
        public static string EditOrder {
            get {
                return ResourceManager.GetString("EditOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bestelregel wijzigen.
        /// </summary>
        public static string EditOrderLine {
            get {
                return ResourceManager.GetString("EditOrderLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product wijzigen.
        /// </summary>
        public static string EditProduct {
            get {
                return ResourceManager.GetString("EditProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Productgroep wijzigen.
        /// </summary>
        public static string EditProductGroup {
            get {
                return ResourceManager.GetString("EditProductGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoerwaarschuwing.
        /// </summary>
        public static string InputWarning {
            get {
                return ResourceManager.GetString("InputWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er zijn 1 of meerdere waarschuwingen actief voor uw invoer. Wilt u doorgaan met opslaan?.
        /// </summary>
        public static string InputWarningMessage {
            get {
                return ResourceManager.GetString("InputWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoer invalide.
        /// </summary>
        public static string InvalidInput {
            get {
                return ResourceManager.GetString("InvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er zijn 1 of meerdere validatiefouten opgetreden. Controleer uw invoer..
        /// </summary>
        public static string InvalidInputMessage {
            get {
                return ResourceManager.GetString("InvalidInputMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to André&apos;s bestelsysteem.
        /// </summary>
        public static string OrderSystemTitle {
            get {
                return ResourceManager.GetString("OrderSystemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opslaan.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
    }
}
