//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderSystem.Data.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OrderResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OrderResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OrderSystem.Data.Resources.OrderResources", typeof(OrderResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product mag niet leeg zijn.
        /// </summary>
        public static string EmptyProductNotAllowed {
            get {
                return ResourceManager.GetString("EmptyProductNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id mag niet leeg zijn.
        /// </summary>
        public static string IdCannotBeEmpty {
            get {
                return ResourceManager.GetString("IdCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id moet uniek zijn.
        /// </summary>
        public static string IdMustBeUnique {
            get {
                return ResourceManager.GetString("IdMustBeUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er zijn meerdere bestelregels met hetzelfde product.
        /// </summary>
        public static string MoreThanOneLineForSameProduct {
            get {
                return ResourceManager.GetString("MoreThanOneLineForSameProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naam.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naam mag niet leeg zijn.
        /// </summary>
        public static string NameCannotBeEmpty {
            get {
                return ResourceManager.GetString("NameCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bestelling moet minimaal 1 bestelregel bevatten.
        /// </summary>
        public static string NeedToOrderAtLeast1Item {
            get {
                return ResourceManager.GetString("NeedToOrderAtLeast1Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De prijs mag niet negatief zijn.
        /// </summary>
        public static string NegativePriceNotAllowed {
            get {
                return ResourceManager.GetString("NegativePriceNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bestelling.
        /// </summary>
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De bestelling kan niet in de toekomst geplaatst worden.
        /// </summary>
        public static string OrderCannotBePlaceInFuture {
            get {
                return ResourceManager.GetString("OrderCannotBePlaceInFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BestellingsId.
        /// </summary>
        public static string OrderId {
            get {
                return ResourceManager.GetString("OrderId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bestelregel.
        /// </summary>
        public static string OrderLine {
            get {
                return ResourceManager.GetString("OrderLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bestelregels.
        /// </summary>
        public static string OrderLines {
            get {
                return ResourceManager.GetString("OrderLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bestellingen.
        /// </summary>
        public static string Orders {
            get {
                return ResourceManager.GetString("Orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geplaatst op.
        /// </summary>
        public static string PlacedAt {
            get {
                return ResourceManager.GetString("PlacedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prijs.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stuksprijs.
        /// </summary>
        public static string PricePerUnit {
            get {
                return ResourceManager.GetString("PricePerUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Productgroep.
        /// </summary>
        public static string ProductGroup {
            get {
                return ResourceManager.GetString("ProductGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Productgroep mag niet leeg zijn.
        /// </summary>
        public static string ProductGroupCannotBeEmpty {
            get {
                return ResourceManager.GetString("ProductGroupCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProductgroepId.
        /// </summary>
        public static string ProductGroupId {
            get {
                return ResourceManager.GetString("ProductGroupId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Productgroepsnaam.
        /// </summary>
        public static string ProductGroupName {
            get {
                return ResourceManager.GetString("ProductGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Productgroepen.
        /// </summary>
        public static string ProductGroups {
            get {
                return ResourceManager.GetString("ProductGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProductId.
        /// </summary>
        public static string ProductId {
            get {
                return ResourceManager.GetString("ProductId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Productnaam.
        /// </summary>
        public static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Producten.
        /// </summary>
        public static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aantal.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er dient minimaal 1 item in deze orderregel besteld te worden.
        /// </summary>
        public static string QuantityCannotBeTooLow {
            get {
                return ResourceManager.GetString("QuantityCannotBeTooLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let op: U verkoopt dit product gratis.
        /// </summary>
        public static string SellingProductForFree {
            get {
                return ResourceManager.GetString("SellingProductForFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtotaal.
        /// </summary>
        public static string SubTotal {
            get {
                return ResourceManager.GetString("SubTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Totaalprijs.
        /// </summary>
        public static string TotalPrice {
            get {
                return ResourceManager.GetString("TotalPrice", resourceCulture);
            }
        }
    }
}
